### ISSUE TITLE
Update Blackbox

### ISSUE THREAD

**Issue by TheMisterEletric** [3scale-ops/prometheus-exporter-operator#40]
Hello,
Currently the version in use of blackbox is 0.18.0 but the last release was 0.22.0.
Is Possible to change the version?

**Comment by slopezz** [comment]
Hi @TheMisterEletric 

Default blackbox exporter image has been updated to `v0.22.0` on https://github.com/3scale-ops/prometheus-exporter-operator/pull/41

And it is available to deploy since https://github.com/3scale-ops/prometheus-exporter-operator/releases/tag/v0.6.1

However, you don't need to wait for a operator release to update any exporter image, at any time you can override the default exporter image using the **PrometheusExporter** CR field called `spec.image.version`, example:

```yaml
apiVersion: monitoring.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: staging-blackbox
spec:
  type: probe
  configurationConfigmapName: prometheus-exporter-probe-staging-blackbox
  image:
    version: v0.22.0
```

You can see a full example of the kind of fields that can be override at any time at https://github.com/3scale-ops/prometheus-exporter-operator/blob/main/docs/prometheus-exporter-crd-reference.md#full-cr-example

The release will be shortly published to OperatorHub.
